name: Build & SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      # Versão v4 (mais estável)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Versão v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib coverage

      - name: Run Tests & Coverage
        run: |
          # Descobre testes na pasta 'tests' e considera a raiz como source
          echo "Rodando testes automatizados..."
            coverage run -m unittest discover -s tests -t .
            coverage xml

      # Versão master do Sonar
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token padrão do GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token atualizado do SonarCloud
