name: Build & SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f4633668828c0807b554c59532332f53 # v4.1.1
        with:
          fetch-depth: 0 # Para análise do Sonar

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib coverage

      - name: Run Tests & Coverage
        run: |
          coverage run -m unittest sistema_ong_ddd.py || true
          coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@49e6cd3b187936a73b8280d59ffd9da69df63ec9 # v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Gerado auto pelo GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Definido nas configurações do repositório
